### ISSUE TITLE
Is the gem actively maintained? 

### ISSUE THREAD

**Issue by siba2893** [cuber-cloud/cuber-gem#15]
Her Marco, I wonder if the gem is actively maintain, cause I would like to host an app on Digital Ocean but I'm worried this is not maintain anymore.

I saw some PRs but this haven't been merged and they are now 9 month old.

**Comment by collimarco** [comment]
Yes, this gem is actively maintained.

We currently use it:
- for our main project Pushpad
- for our new projects launched this year (Newsletter.page)
- and many others

Stay assured that this project is live and maintained.

Simply, there isn't anything to change at the moment, it's stable. Also, it doesn't have any gem dependencies (by design), so it doesn't require frequent updates.
